import Head from "next/head";
import SideNavBar from "./components/SideNavbar.jsx"

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Tafakna Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavBar/>
    </div>
  );
}
